### ISSUE TITLE
Cannot find module 'feathers-reactive'.

### ISSUE THREAD

**Issue by patrickpereira** [feathersjs/feathers-reactive#52] opened 2017-04-15 18:53 UTC
Hi guys,

I'm trying to use feathers reactive in a angular cli project, all other feather modules are imported fine, except from feathers-reactive.

I keep getting Cannot find module 'feathers-reactive'., when I'm compiling.
I'm using latest version of feathers-reactive and I'm using angular/cli": "1.0.0-beta.32.3

I can see that the feathers-reactive folder is correctly in node_modules.

Is there any other way to import it? I'm doing this currently: import * as reactive from 'feathers-reactive';

Best regards
Patrick

**Comment by patrickpereira** [comment] 2017-04-15 18:56
If I import it like this, it works: const reactive = require('feathers-reactive');

I'm not sure why the above is the case, as all other feathers plugins I can use the import statement.

**Comment by eddyystop** [comment] 2017-04-15 19:40
Could this be your issue? https://github.com/webpack/webpack/issues/1794

**Comment by daffl** [comment] 2017-04-16 23:35
I think @eddyystop got it. It will work with

```js
 import reactive from 'feathers-reactive';
// or
const reactive = require('feathers-reactive');
```

**Comment by patrickpereira** [comment] 2017-04-17 04:10
The first gives me this error:
ERROR in /Users/patrickpereira/lazy/backend/src/app/shared/api/api.service.ts (11,22): Cannot find module 'feathers-reactive'.)

Second one is working, so I'm just using that.

**Comment by daffl** [comment] 2017-04-17 04:17
That seems odd. I'll give it another try.

**Comment by j2L4e** [comment] 2017-05-02 10:58
@patrickpereira create a .d.ts file containing `declare module 'feathers-reactive'`

**Comment by eddyystop** [comment] 2017-05-02 12:44
Watch out @j2L4e , you are becoming our TS guy !

**Comment by daffl** [comment] 2017-08-28 18:12
This TypeScript files has been updated in the recently released v0.5.0 so I am going to close this.

**Comment by daffl** [comment] 2017-08-29 22:04
Still seems to be happening. @j2L4e If you get a chance, could you check if latest works with https://github.com/feathersjs/feathers-chat-angular ?

**Comment by oscarhull** [comment] 2017-08-29 22:42
Still failing, steps to reproduce:

1) Download https://github.com/feathersjs/feathers-chat-angular
2) Update feathers-reactive version to 0.5.0 in package.json
3) run: `npm install`
4) run: `ng serve`

** Note ** I tried this but didn't work: Try adding `declare module 'feathers-reactive'` to `node_modules/feathers-reactive/index.d.ts`

Result:

```
ERROR in ./src/app/services/feathers.service.ts
Module not found: Error: Can't resolve 'feathers-reactive' in '/Users/ohull/Downloads/feathers-chat-angular-master/src/app/services'
 @ ./src/app/services/feathers.service.ts 12:0-48
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

**Comment by patrickpereira** [comment] 2017-08-30 03:48
I made it work like this in Angular 4:

import * as reactive from 'feathers-reactive/lib';

**Comment by j2L4e** [comment] 2017-08-30 08:28
I started a new angular (cli version 1.3.2) project with feathers-reactive 0.5.0 yesterday and it works just fine. I'll investigate.

**Closed** 2017-08-30 18:11 UTC
